[self]
name = "blender_theme"
version = "0.1.0"
description = "Original Blender Dark Theme"
license = "GPL-3.0-or-later"
notices = [
  "11 of the WIPO copyright treaty adopted on 20 December 1996, or",
  "<program>  Copyright (C) <year>  <name of author>",
  "Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>",
  "Copyright (C) <year>  <name of author>",
]
repository = "https://github.com/ameknite/blender_theme"
